siteTitle = "Aditi Rajagopal"
siteDescr = "Website, Portfolio and #Extra"
siteAuthor = "Aditi Rajagopal"

twitterId = "aditi_rajagopal"
googleAnalyticsId = ""
linkPrefix = "/gatsby-starter-bootstrap"
