siteTitle = "Aditi Rajagopal"
siteDescr = "Website, Portfolio and #Extra"
siteAuthor = "aditi_rajagopal"

twitterId = "aditi_rajagopal"
googleAnalyticsId = ""
linkPrefix = "/gatsby-starter-bootstrap"
